APIVersion: v1.10.2
name: WordPress-Distribution
type: wordpress
docroot: ""
php_version: "7.2"
webserver_type: apache-fpm
router_http_port: "80"
router_https_port: "443"
xdebug_enabled: false
additional_hostnames: []
additional_fqdns: []
mariadb_version: "10.2"
nfs_mount_enabled: false
provider: default
use_dns_when_possible: true
timezone: Europe/Berlin
hooks:
  post-start:
    ## download and install wordpress
    - exec: "wp core download --locale=$WP_DDEV_LOCALE --version=$WP_DDEV_VERSION"
    - exec: "wp config create --dbname=db --dbuser=db --dbpass=db --dbhost=db"
    - exec: "wp core install --url=https://$VIRTUAL_HOST --title=$WP_DDEV_TITLE --admin_user=$WP_DDEV_ADMIN_USER --admin_email=$WP_DDEV_ADMIN_EMAIL"
    ## get new salts for your wp-config.php file
    - exec: "wp config shuffle-salts"
    ## more ram and less more security
    - exec: "wp config set WP_POST_REVISIONS false --raw --add"
    - exec: "wp config set WP_MEMORY_LIMIT 256M --add"
    - exec: "wp config set WP_MAX_MEMORY_LIMIT 256M --add"
    - exec: "wp config set DISALLOW_FILE_EDIT true --raw"
    ## wordpress debug mode for developers
    #- exec: "wp config set WP_DEBUG true --raw --add"
    #- exec: "wp config set WP_DEBUG_LOG true --raw --add"
    #- exec: "wp config set WP_DEBUG_DISPLAY false --raw --add"
    #- exec: "wp config set SCRIPT_DEBUG true --raw --add"
    #- exec: "wp config set SAVEQUERIES true --raw --add"
    ## empties a site of its content (posts, comments, terms, and meta)
    - exec: "wp site empty --uploads --yes"
    ## delete all default plugins
    - exec: "wp plugin delete --all"
    ## delete the default blogdescription
    - exec: "wp option update blogdescription ''"
    ## hide for the search engines
    - exec: "wp option update blog_public 0"
    ## disable the avatars
    - exec: "wp option update show_avatars 0"
    ## install and activate some plugins
    - exec: "wp plugin install antispam-bee --activate"
    - exec: "wp plugin install statify --activate"
    ## after installing all plugins, update the language
    - exec: "wp language plugin install --all $WP_DDEV_LOCALE"
